Add support for Made With CNC Handheld Console
PocketNC/Settings pull request #1
Opened 2022-10-04 23:09 UTC by liqdfire

Add userspace component to add support for a Made With CNC Handheld Console.

2022-10-11 18:00 UTC, jallwine requested changes

2022-10-11 18:00 UTC, jallwine commented on features/handheld_console/overlay.inc
> +BUTTON_0_SIGNAL=feed-hold-3
I would use feed-hold-5, cycle-start-5 and abort-5 to be on the safe side. I know for sure we're using feed-hold-3 for our safety switch enclosure and feed-hold-4 for our high speed spindle machines. Users with those features could override them, but using 5 will avoid those conflicts.

2022-10-11 18:00 UTC, jallwine commented on features/handheld_console/handheld_console.py
> +#!/usr/bin/python3
This file needs to be made executable.

2022-10-17 16:03 UTC, jallwine reviewed
- The selectAxis function doesn't adequately deselect the B axis because range(1,5) iterates over 1, 2, 3 and 4.
- The rotary axis increments are very small. Perhaps add options for customizing the increment values?
- At start up, the handheld_console pins don't sync properly.

2022-10-19 18:35 UTC, jallwine commented
I think 36 is too high for a default base rotary increment. I would choose either 3.6 if you think a quarter turn of the dial should result in a 90 degree movement at the largest increment or 1 if the largest increment should be tied to the numbers on the dial (so a 90 degree movement when starting at 0 and turning the dial to 90).

I'll accept this pull request with either of those changes.

If you want to go the next step and allow a user to customize those values on the fly with M codes, the selected-linear-jog-incr and selected-rotary-jog-incr pins should probably get sync'd on a jog event rather than only in selectJogIncrement.

2022-10-27 18:04 UTC, liqdfire commented
Modified the base jog increments for rotary axes to 1 degree.

2022-10-27 18:56 UTC, merged